version: "3.9"
services:
  nextchat-changcheng:
    profiles: [ "no-proxy" ]
    container_name: nextchat-changcheng
    image: baibaomen/nextchat-changcheng:v1
    ports:
      - 443:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - CUSTOM_MODELS=$CUSTOM_MODELS
      - DEFAULT_MODEL=$DEFAULT_MODEL

  nextchat-changcheng-proxy:
    profiles: [ "proxy" ]
    container_name: nextchat-changcheng-proxy
    image: baibaomen/nextchat-changcheng:v1
    ports:
      - 443:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
      - CODE=$CODE
      - PROXY_URL=$PROXY_URL
      - BASE_URL=$BASE_URL
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - CUSTOM_MODELS=$CUSTOM_MODELS
      - DEFAULT_MODEL=$DEFAULT_MODEL
